# Jupyter 快捷键
- 模式切换
    - esc 切换到命令模式
    - Enter 切换到编辑模式
- 编辑模式常用快捷键
    - Ctrl + ]缩进
    - Ctrl + Y 重做
    - Ctrl + Enter 运行当前单元
    - Shift + Enter 运行当前单，若无下一个单元，则新建下一个单元
    - Alt + Enter 运行当前单元，并新建下一个单元
- 命令模式常用快捷键
    - Y:原单元转为 code
    - M:原单元转为 Markdown
    - R:原单元转为 源码格式
    - A:在上方插入新单元
    - B:在下方插入新单元
    - DD:删除单元
    - LL:中断内核
    - OO:重启内核

# 1. 什么是PyTorch?

[PyTorch](https://pytorch.org/)是一个基于Python的科学计算库，它有如下特点：
- 类似于Numpy,但是它可以使用GPU
- 可以用它定义深度学习模型，可以灵活的进行深度学习模型的训练和使用
- Tensors Tensor类似于Numpy的ndarray,唯一的区别是前者可以在GPU上加速运算

## 1.1 Tensors
- 导入torch

In [7]:
import torch

- 构造一个未初始化的矩阵：shape=5x3

In [10]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

- 构建一个随机初始化矩阵：shape=5x3

In [11]:
x = torch.rand(5, 3)
print(x)

tensor([[0.9107, 0.7353, 0.4210],
        [0.3232, 0.2024, 0.1266],
        [0.2547, 0.8111, 0.0194],
        [0.9602, 0.5498, 0.5110],
        [0.6287, 0.8993, 0.7994]])


- 构建一个全为0的，数据类型为long的矩阵：shape=5x3

In [12]:
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


- 从数据中直接构建Tensor

In [16]:
y = [5, 3]
x = torch.tensor(y)
print(x)
print(id(x))
print(id(y))

tensor([5, 3])
1879043711688
1879043521928


- 也可以从一个已有的tensor构建一个tensor。这些方法会重用原来tensor的特征，如数据类型和数据等

In [34]:
x = x.new_ones(5, 3)   # new_*这个方法需要传递新tensor的sizes,也就是矩阵的形状
print(x)

y = torch.rand_like(x, dtype=torch.float)    # 穿甲一个与x形状相似的随机矩阵
print(y)

print(x.shape)
print(y.size())    # shape和size() 都是获取tensor的形状

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor([[0.6975, 0.3096, 0.5050],
        [0.9831, 0.2105, 0.3983],
        [0.7223, 0.0028, 0.5541],
        [0.1235, 0.6245, 0.2283],
        [0.7322, 0.2845, 0.8687]])
torch.Size([5, 3])
torch.Size([5, 3])


## 1.2 Tensor的运算    

- 加法

In [35]:
print(x)
print(y)
print(x+y)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor([[0.6975, 0.3096, 0.5050],
        [0.9831, 0.2105, 0.3983],
        [0.7223, 0.0028, 0.5541],
        [0.1235, 0.6245, 0.2283],
        [0.7322, 0.2845, 0.8687]])
tensor([[1.6975, 1.3096, 1.5050],
        [1.9831, 1.2105, 1.3983],
        [1.7223, 1.0028, 1.5541],
        [1.1235, 1.6245, 1.2283],
        [1.7322, 1.2845, 1.8687]])


- add加法

In [36]:
print(torch.add(x, y))

tensor([[1.6975, 1.3096, 1.5050],
        [1.9831, 1.2105, 1.3983],
        [1.7223, 1.0028, 1.5541],
        [1.1235, 1.6245, 1.2283],
        [1.7322, 1.2845, 1.8687]])


- 把加法的输出结果作为一个变量

In [42]:
result = torch.empty(5, 3)
print(result)
torch.add(x, y, out=result)
print(result)

tensor([[1.6975, 1.3096, 1.5050],
        [1.9831, 1.2105, 1.3983],
        [1.7223, 1.0028, 1.5541],
        [1.1235, 1.6245, 1.2283],
        [1.7322, 1.2845, 1.8687]])
tensor([[1.6975, 1.3096, 1.5050],
        [1.9831, 1.2105, 1.3983],
        [1.7223, 1.0028, 1.5541],
        [1.1235, 1.6245, 1.2283],
        [1.7322, 1.2845, 1.8687]])


- in-place加法 （in-place:原地取代的意思）

In [45]:
y = torch.zeros(x.size())
print(y)
y.add_(x)
print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


- **注意：*
    - 所有in-place运算都会的名称都是一下划线"_"结尾，这种运算会直接改变被操作变量的值


## 1.3 Tensor的索引操作

In [46]:
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


In [48]:
print(x[:,1])   # 取x的第1列，列标从0开始

tensor([1, 1, 1, 1, 1])


- Resizing:如果希望reshape tensor的形状可以使用：torch.view()

In [49]:
x = torch.ones(4, 4)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [50]:
y = x.view(2, 8)
print(y)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])


- 通过设置一个维度为“-1”来进行自动推断tensor的形状

In [54]:
z = x.view(-1,2,2)
print(z)
print(z.size())

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])
torch.Size([4, 2, 2])


- 如果tensor中只包含一个元素，可以使用“.item()”方法，把tensor中的数值变成python的数值

In [58]:
x = torch.ones(1)
print(x)
print(x.item())
print(type(x))
print(type(x.item()))

tensor([1.])
1.0
<class 'torch.Tensor'>
<class 'float'>


## 1.4 Numpy和Tensor之间的转换

- Torch Tensor可以和Numpy array无障碍的转换
- Tensor 和 Numpy array之间会共享同一块数据内存，所以改变其中之一，两者的数据都会发生变化
- 所有CPU上的Tensor都支持转成numpy或者从numpy转成Tensor

- Tensor 转Numpy Array :   “.numpy()方法”

In [61]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [64]:
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


- 通过修改tensor的值来修改numpy中的值

In [68]:
print(id(a))
print(id(b))
# 修改tensor的值
a.add_(1)
print(a)
print(b)
print(id(a))
print(id(b))

1879043970456
1879043967472
tensor([4., 4., 4., 4., 4.])
[4. 4. 4. 4. 4.]
1879043970456
1879043967472


- Numpy ndarray 转 tensor

In [72]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)
np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## 1.5 CUDA Tensors

".to()"方法，将tensor转移到GPU上运行,也可以把GPU上的数据转移到CPU上运行

In [79]:
if torch.cuda.is_available():
    gpu = torch.device('cuda')            # 获取GPU
    x = torch.ones(4)                     # 创建一个CPU的tensor
    y = torch.ones_like(x, device=gpu)    # 创建tensor的时候给它指定GPU
    x = x.to(gpu)                         # 把x转移到GPU上
    z = x + y
    print(z)
    print(z.to('cpu', torch.double))

tensor([2., 2., 2., 2.], device='cuda:0')
tensor([2., 2., 2., 2.], dtype=torch.float64)


# 2. 全连接神经网络

## 2.1 numpy实现两层全连接神经网络

- 一个全连接ReLU神经网络，一个隐藏层，没有bias。用来从x预测y,使用$L_{2}$Loss

- 这一实现完全使用numpy来计算前向神经网络，loss，和反向传播


- numpy ndarray 是一个普通的n为array。它不知道任何关于深度学习或者梯度的知识，也不知道计算图，只能是一种运来计算数学运算的数据结构。



In [ ]:
import numpy as np

N, D_in, H, D_out = 4, 100,20,10   # N是batch, D_in是输入维度，H为隐藏层维度，D_OUT为输出维度

# 创建输入输出数据
x = np.random.randn(N, D_in)
Y = np.random.randn(N, D_out)

# 初始化权重参数
w1 = np.random.rand(D_in, H)
W2 = np.random.rand(H, D_out)

# 学习率
lr = le-6

for t in range(500):
    # 前向过程
    h = x.dot(w1)
    h_relu = np.maximum(h, 0 )
    y_pred = h_relu.dot(w2)
    
    # 计算损失函数
    loss = np.square(y_pred -y).sum()
    print(t, loss)
