# 2.1. 数据操作
## 2.1.1. 入门
- <font size=4> torch.arang()创建一维数组

In [46]:
import torch
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"  # 配置单元格支持多个输出
x = torch.arange(12)  # torch.arange()方法创建长度为12的一维数组，从0到11
# print(x)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

- <font size=4>通过张量的shape属性来查看张量的维度和大小，也就是查看张量（沿每个轴的长度）的形状 

In [7]:
x.shape

torch.Size([12])

- <font size=4>可以通过张量的size()方法来查看张量的形状和大小

In [13]:
x.size()  # 属性和方法的区别，属性不需要括号，方法需要加上括号

torch.Size([12])

- <font size=4>可以通过张量的numel()方法来查看张量的元素的个数

In [37]:
x.numel()

12

- <font size=4>可以通过张量的reshape()函数来改变张量的形状，但是这个过程不会改变张量的元素的值

In [45]:
x
x1 = x.reshape(3, 4)  # 将x是1行12列，修改为3行4列
x1

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

- <font size=4>张量的reshape()方法还能自动推理改变张量维度大小的一个维度，用“-1”代替该维度的值

In [21]:
x.reshape(-1,2)  # 比如该列中，只给了将1行12列的张量x转为2列6行的张量，只要显性的给出任意一个维度的值，另一维度用-1代替，reshape()方法会自动推断另一维度的大小

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])

In [47]:
x.reshape(2,2,-1)  # 该例中，自动推断了2个2行3列的张量


tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])